export const DUMMY_MESSAGES = [
  {
    id: 1,
    type: "group",
    name: "Frontend Masterclass 🚀",
    text: "Grace: Ayo masuk ke zoom meetingnya sekarang!",
    time: "12:30",
    color: "#38BDF8",
    emoji: "👨‍💻",
    unread: 3,
  },
  {
    id: 2,
    type: "personal",
    name: "Carloz",
    text: "Pe, info mabar ntar malem",
    time: "11:30",
    color: "#FB923C",
    emoji: "👦",
    unread: 1,
  },
  {
    id: 3,
    type: "personal",
    name: "Ashly",
    text: "p, udanh ngerjain tugasnya belum?",
    time: "10:30",
    color: "#F472B6",
    emoji: "👩",
    unread: 0,
  },
  {
    id: 4,
    type: "group",
    name: "UI/UX Enthusiast 🎨",
    text: "Donatur: Ada yang mau review design figma saya?",
    time: "08:30",
    color: "#FACC15",
    emoji: "✨",
    unread: 5,
  },
  {
    id: 5,
    type: "personal",
    name: "Leonor",
    text: "Ikut kelasnya ga hari ini???",
    time: "Kemarin",
    color: "#A78BFA",
    emoji: "👱‍♀️",
    unread: 0,
  },
  {
    id: 6,
    type: "personal",
    name: "Chris Redfield",
    text: "Boleh minta catatannya dong bro",
    time: "Kemarin",
    color: "#10B981",
    emoji: "🧔",
    unread: 0,
  },
  {
    id: 7,
    type: "group",
    name: "Komunitas React Indo",
    text: "Leon Scott: Ada yang pernah error hooks ini?",
    time: "Senin",
    color: "#F472B6",
    emoji: "⚛️",
    unread: 12,
  },
];

export const HELP_CATEGORIES = [
  {
    id: 1,
    title: "Panduan Belajar",
    icon: <FiBook />,
    color: "#38BDF8",
    desc: "Cara memulai kursus dan menggunakan fitur kelas.",
  },
  {
    id: 2,
    title: "Pembayaran & Saldo",
    icon: <FiCreditCard />,
    color: "#FACC15",
    desc: "Masalah transaksi, invoice, dan penarikan saldo.",
  },
  {
    id: 3,
    title: "Akun & Keamanan",
    icon: <FiSettings />,
    color: "#A78BFA",
    desc: "Lupa password, verifikasi, dan pengaturan profil.",
  },
  {
    id: 4,
    title: "Kendala Teknis",
    icon: <FiAlertCircle />,
    color: "#F472B6",
    desc: "Bug aplikasi, error akses, dan masalah teknis lainnya.",
  },
];
